readme: Add table of contents
tsconfig/bases pull request #236
Opened 2023-11-11 23:17 UTC by hyperupcall

As per linked issue, adds table at top with bases and their npm package names.

Closes #162

2023-11-12 15:43 UTC, jhae-de requested changes

2023-11-12 15:43 UTC, jhae-de commented on README.md
> +| [Node 19](#node-19-tsconfigjson)                   | [`@tsconfig/node19`](https://npmjs.com/package/@tsconfig/node19)                     |
The sorting is not correct here.
```suggestion
| [Node 19](#node-19-tsconfigjson)                   | [`@tsconfig/node19`](https://npmjs.com/package/@tsconfig/node19)                     |
| [Node 20](#node-20-tsconfigjson)                   | [`@tsconfig/node20`](https://npmjs.com/package/@tsconfig/node20)                     |
```

2023-11-13 16:28 UTC, hyperupcall commented on README.md
> +| [Node 19](#node-19-tsconfigjson)                   | [`@tsconfig/node19`](https://npmjs.com/package/@tsconfig/node19)                     |
fixed

2023-12-11 16:25 UTC, orta commented
Cool, looks good to me - thanks!

2023-12-11 16:25 UTC, merged