Drop `display` field
tsconfig/bases pull request #258
Opened 2024-03-16 07:06 UTC by yinm

resolve: https://github.com/tsconfig/bases/issues/180

2024-03-20 09:04 UTC, orta requested changes
I'm open to this being post-processed out when we are going from the file in this repo to the file in the npm package, but not for removing the display tag inside these json files.

Having _display in ensures that each base json file is fully self contained

2024-03-25 13:58 UTC, yinm commented
Thank you for your review.

I changed code that drop `display` field when generating npm package.
Most of the codes are unusable, so I removed all commits and rebase latest main branch.

Does it accord that you think？

2024-03-25 15:26 UTC, orta commented on bases/recommended.json
> +    "target": "ES2015",
```suggestion
    "target": "ES2016",
```

2024-03-25 15:27 UTC, orta commented
Seems reasonable to me 👍🏻

2024-03-25 15:38 UTC, orta approved these changes

2024-03-26 00:27 UTC, yinm commented on bases/recommended.json
> +    "target": "ES2015",
Fix 7ca1d5c...15ede8e

2024-03-27 00:07 UTC, merged

2024-03-27 00:07 UTC, orta commented
Thanks!